### ISSUE TITLE
Issues with X-Plane 11

### ISSUE THREAD

**Issue by DeshMindER** [joanpc/xJoyMap#4]
First of all thanks for this.

I'm having some issues with X-Plane 11.

This is the xjoymap.ini that I'm using: [xjoymap.zip](https://github.com/joanpc/xJoyMap/files/1171929/xjoymap.zip)

So I set up all the keyboards commands on the settings page. When I close the simulator and open back up, some commands are gone, some aren't.

I'm using:
X-Plane 11 64-bits 11.02r2
Python version 2.7.12
Python Interface 2.73.06
XJoyMap 1.3.0

**Comment by joanpc** [comment]
Hi, 

I didn't try-it on xp11 but it should work. You have the same problem with the provided example file? Are you using the same path x-plane native commands are defined? Don't define commands under sim/ cause it will cause problems.

Let me know.

**Comment by DeshMindER** [comment]
Actually, I just figure it out why it's duplicating. It actually isn't. If I hover the mouse on the duplicated, I can see that's actually the reverse action for it (toogle). X-Plane 11 changed the display of the command.

![image](https://user-images.githubusercontent.com/12618544/28555404-06b6c98a-70d6-11e7-9e99-169499952672.png)


What kind of problems will I encounter? I've set up 3 commands under sim/ because I couldn't find it under the plane

[Altimeter Down]
new_command=Altimeter Down
dataref=sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot 
description=AltimeterDown
increment=-0.02992
type=float
repeat=True

[Altimeter Up]
new_command=Altimeter Up
dataref=sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot 
description=AltimeterUp
increment=0.02992
type=float
repeat=True

[Altimeter STD]
new_command=Altimeter STD
dataref=sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot 
description=AltimeterSTD
values: 29.92
type=float
repeat=False

**Comment by joanpc** [comment]
I'm not talking about the datatef, just the command, you can specify all the command path for the "new_command" definition.

I'm not sure the command accepts spaces. Try removing the spaces from the new_command definitions or replace them with underscores _.


[Altimeter STD]
new_command=**Altimeter_STD**

**Comment by DeshMindER** [comment]
I'm not specifying, just leaving as it is I think. Here's the contents of my file. I removed all the spaces and replaced them with underscores. Maybe that's why some of the keyboards that I set up were not sticking after the restart.

[Dome_Light]
new_command=Dome_Light
dataref=ixeg/733/misc/dome_light_act
description=Dome light
values = -1, 0, 1

[Landing_Lights On]
new_command=Landing_Lights
dataref=ixeg/733/lighting/land_light_all_act
description=Landing Lights
on_value = 1
off_value = 0

[Wipers]
new_command=Wipers
dataref:ixeg/733/wiper/wiper_speed_act
description=Wipers On
values = 0, 1, 2

[Terrain]
new_command=Terrain
dataref=ixeg/733/wxr/wxr_disp_terrain_act
description=Terrain
values = 0, 1

[Wx_Toogle]
new_command=Wx_Toogle
dataref=ixeg/733/wxr/wxr_onoff_act
description=Wx Toggle
values = 0, 1

[Recall]
new_command=Recall
dataref=ixeg/733/caution/caution_reset_act
description=Recall
values = 0, 1

[Seatbelts]
new_command=Seatbelts
dataref=ixeg/733/misc/seatbelt_act
description=Seatbelts
values = 0, 2

[Clock]
new_command=Clock
dataref=ixeg/733/clock/clock_chr_pt_act
description=Clock
values = 1, 1

[Transponder]
new_command=Transponder
dataref=ixeg/733/xpdr/xpdr_stby_act
description=Transponder
values = 0, 2

[Mins_up]
new_command=Baro_up
dataref=ixeg/733/ehsi/dh_pt_act
description=BaroUp
increment=1
type=float
repeat=True

[Mins_down]
new_command=Baro_down
dataref=ixeg/733/ehsi/dh_pt_act
description=BaroCPDn
increment=-1
type=float
repeat=True

[Altimeter_Down]
new_command=Altimeter_Down
dataref=sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot 
description=AltimeterDown
increment=-0.02992
type=float
repeat=True

[Altimeter_Up]
new_command=Altimeter_Up
dataref=sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot 
description=AltimeterUp
increment=0.02992
type=float
repeat=True

[Altimeter_STD]
new_command=Altimeter_STD
dataref=sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot 
description=AltimeterSTD
values: 29.92
type=float
repeat=False

**Comment by joanpc** [comment]
The plugin will add some additional commands, for example the _rev is for reversed order/increments so you don't have to define up and down commands by hand.

**Comment by joanpc** [comment]
Should work now... 

Does it? 

:)

**Comment by DeshMindER** [comment]
I'm testing right now. By the way sir, is there any way to use one command for 2 actions?

For instance, I would like the following command to change both the "sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot" and the "sim/cockpit2/gauges/actuators/barometer_setting_in_hg_copilot".

Or a way to set up the same key for two different commands.

I tried to understand it under the readme file, but couldn't figure out a way.

[Altimeter_STD]
new_command=Altimeter_STD
dataref=sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot
description=AltimeterSTD
values: 29.92
type=float
repeat=False

**Comment by joanpc** [comment]
Yes you have to create a command for each dataref you want to trigger and then use an alias.


buttonAlias:                creates Alias, combo and "shifted" commands and allows to override 

;
; Example combo command
;
; Creates the command LNAV_VNAV that triggers
; LNAV and VNAV simultaneously 
; 
; note: You can also define multiple shifted commands 

[LNAV VNAV toggle combo]
new_command=LNAV_VNAV
main_command=sim/autopilot/NAV, sim/autopilot/vnav

**Comment by joanpc** [comment]
Note that:
main_command=**sim/autopilot/NAV, sim/autopilot/vna**v

**sim/autopilot/NAV and sim/autopilot/vnav** are commands not datarefs.

**Comment by DeshMindER** [comment]
I restarted X-Plane 11 and all of my settings were saved.

For the Combo.. I still don't get it... sorry. I tried the following:

[Altimeter_Both]
new_command=Altimeter_Both
main_command=Altimeter_STDCA, Altimeter_STDCO

[Altimeter_STDCA]
new_command=Altimeter_STDCA
dataref=sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot
description=AltimeterSTDCA
values: 29.92
type=float
repeat=False

[Altimeter_STDCO]
new_command=Altimeter_STDCO
dataref=sim/cockpit2/gauges/actuators/barometer_setting_in_hg_copilot
description=AltimeterSTDCO
values: 29.92
type=float
repeat=False

**Comment by joanpc** [comment]
Should work if you define the combo after the commands. Otherwise the
plugin won't be able to resolve the commands.

**Comment by DeshMindER** [comment]
That makes sense. But it didn't work.

**Comment by joanpc** [comment]
Try defining the command with the complete route.

[Altimeter_Both]
new_command=Altimeter_Both
main_command=xjoymap/main/Altimeter_STDCA, xjoymap/main/Altimeter_STDCO

**Comment by DeshMindER** [comment]
Thanks man ! That worked!

One more thing that I noticed. Let's suppose I have a command that incremends a value by 1:

Ex.:

increment=1

If I go into the Python Interface.. and "Enable/Disable" script. And toggle xjoymap, the first time it resets. If I toogle it again, somehow the increment value now is 2. If I do it again, the increment goes up to 3 and so on.

**Comment by DeshMindER** [comment]
Joan,

Thanks again for all the help.

When I write multiple combos, on the simulator, it shows the name of only one of them. Repeated. But they are all different. For instance:

[Flight_Director_Both]
new_command=Flight_Director_Both
main_command=xjoymap/main/zFlight_Director_Pilot, xjoymap/main/zFlight_Director_CoPilot

[Altimeter_STDALL]
new_command=Altimeter_STDALL
main_command=xjoymap/main/zAltimeter_STDCA, xjoymap/main/zAltimeter_STDCO, xjoymap/main/zAltimeter_STDCT

[Altimeter_DownALL]
new_command=Altimeter_DownALL
main_command=xjoymap/main/zAltimeter_DownCA, xjoymap/main/zAltimeter_DownCO, xjoymap/main/zAltimeter_DownCT

![image](https://user-images.githubusercontent.com/12618544/28741587-dd30749a-73ef-11e7-822b-3e93123c359b.png)

As you can see, it seems that the only available command is Altimeter_DownAll. However, the other two are just mislabeled.

Shift+z is the Altimeter_DownAll
Shift+y is the Altimeter_STDALL
Shift+Ctrl+G is the Flight_Director_Both

I did delete the file X-Plane Keys.prf to test. But no Joy.

EDIT:

I did add the Description=      after each combo, now if I hover the mouse, at least I know which one is which.

**Comment by joanpc** [comment]
That's really weird. I rechecked the code, all seems ok to me. May be some xp10 issue, I'm not really sure and I don't have time to test-it.

**Comment by DeshMindER** [comment]
Not a problem! Thanks for this great plugin!
